### ISSUE TITLE
Document new IPC support

### ISSUE THREAD

**Issue by jmcph4** [OffchainLabs/arbitrum-docs#34]
**Is your feature request related to a problem? Please describe.**
IPC support [recently landed](https://github.com/OffchainLabs/nitro/pull/1156) in the [2.0.7 release](https://github.com/OffchainLabs/nitro/releases/tag/v2.0.7). Notably, the official documentation for [running a Nitro node](https://developer.arbitrum.io/node-running/running-a-node) currently lacks instructions on how to run a Nitro node both:

 - In Docker, and
 - Exposing the node's IPC capabilities

**Describe the solution you'd like**
Instructions added to the official documentation for operating a Nitro node that includes (working) commands for starting the node from within Docker and that is able to communicate with host processes via IPC.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by ymonye** [comment]
Hey all, any luck here? I by chance found this thread under the Discord since I was wondering the same thing (for much faster JSON-RPC calls).

**Comment by ymonye** [comment]
@jmcph4, I found your thread in Discord since I was wondering the same. Here's how I had IPC working under Docker on RHEL/AlmaLinux/Rocky Linux 8.5. I'm also running both Go-Ethereum & Arbitrum Classic Docker images under the same "eth-mainnet" Docker network.

docker run -d -it --ulimit nofile=1000000:1000000 --restart unless-stopped --stop-timeout 300 --log-opt max-size=10m --name arbitrum-nitro-mainnet --net eth-mainnet -v /arbitrum/nitro/mainnet/:/home/user/.arbitrum -p 0.0.0.0:8549:8549 -p 0.0.0.0:8550:8550 offchainlabs/nitro-node:v2.0.9-51f9452 --l1.url http://eth-mainnet:8545 --l2.chain-id=42161 --http.api=net,web3,eth,debug --http.corsdomain=* --http.addr=0.0.0.0 --http.port=8549 --http.vhosts=* --ws.addr=0.0.0.0 --ws.port=8550 --init.url="https://snapshot.arbitrum.io/mainnet/nitro.tar" --node.rpc.classic-redirect=http://eth-mainnet:8547 --node.caching.archive --ipc.path="/home/user/.arbitrum/arbitrum.ipc"
