### ISSUE TITLE
Docs update request: /node-running/how-tos/running-a-full-node

### ISSUE THREAD

**Issue by f00stx** [OffchainLabs/arbitrum-docs#551]
Source: https://docs.arbitrum.io/node-running/how-tos/running-a-full-node

Request: There seems to be a step or info missing, as I've tried to start up a node following the instructions, but I get this error:

`WARN [09-12|22:38:43.333] error connecting to L1   err="x509: certificate is valid for ingress.local, not main-light.eth.linkpool.io"`

It repeats a few times then exits for "too many errors trying to connect to L1".

Does this come down to the choice of L1 RPC endpoint, or is there a step missing in the docs for configuring certs etc?

**Comment by hkalodner** [comment]
You'll have better luck reaching out on discord if you need more help, but it seems like your issue is that the the L1 rpc isn't setup to be able to connect from whereever you're running your node. I'm guessing if you run `curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","id":"latest"}' https://l1-url`
` you'll get a similar error
